/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CargoDAO;
import dao.EmpresaDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import main.Cargo;
import main.Empresa;
import model.PesquisaTableModel;

/**
 *
 * @author lucas
 */
public class CadCargos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadEmpresas
     */
    private String titulo = "Pesquisar Cargos";
    private final String[] colunas = {"Código", "Cargo"};
    private final String modelo = "Cargo";
    private TelaPrincipal auxTP;
    
    public CadCargos(TelaPrincipal aux) {
        initComponents();
        auxTP = aux;
    }

    public JTextField getjTFCargo() {
        return jTFCargo;
    }

    public JTextField getjTFCod() {
        return jTFCod;
    }
    
    public void limparCampos(){
        jTFCod.setText("");
        jTFCargo.setText("");
    }
    
    public void cadastrarCargo(){
        Cargo cargo = new Cargo();
        CargoDAO cargoDAO = new CargoDAO();
        
        cargo.setCargo(jTFCargo.getText());
        
        cargoDAO.insert(cargo);
        
        limparCampos();
        jTFCod.requestFocus();
    }
    
    public void alterarCargo(){
        Cargo cargo = new Cargo();
        CargoDAO cargoDAO = new CargoDAO();
        
        cargo.setCargo(jTFCargo.getText());
        
        cargoDAO.update(cargo);
        
        limparCampos();
        jTFCod.requestFocus();
    }
    
    public void excluirCargo(){
        Cargo cargo = new Cargo();
        CargoDAO cargoDAO = new CargoDAO();
        
        cargo.setCodCargo(Integer.parseInt(jTFCod.getText()));
        
        cargoDAO.delete(cargo);
        
        limparCampos();
    }
    
    public void preencherCampos(){
        CargoDAO cargoDAO = new CargoDAO();
        List<Cargo> dados = cargoDAO.selectByCod(Integer.parseInt(jTFCod.getText()));
        if (dados.size() == 0) {
            JOptionPane.showMessageDialog(null, "Novo registro!", "Aviso", JOptionPane.OK_OPTION);
            limparCampos();
            jTFCargo.requestFocus();
        }else{
            jTFCargo.setText(String.valueOf(dados.get(0).getCargo()));
            jTFCargo.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTFCargo = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTFCod = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Cargos");

        jLabel3.setText("Cargo");

        jTFCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCargoKeyPressed(evt);
            }
        });

        jBtnPesquisar.setText("...");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });
        jBtnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnSalvarKeyPressed(evt);
            }
        });

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLabel6.setText("Código");

        jTFCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFCargo)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFCod, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        if (!jTFCod.getText().equalsIgnoreCase("")) {
            alterarCargo();
        }else{
            cadastrarCargo();
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if(jTFCod.getText() != null){
            excluirCargo();
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTFCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER && jTFCod.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Novo registro!", "Aviso", JOptionPane.OK_OPTION);
            limparCampos();
            jTFCargo.requestFocus();
        }else if(evt.getKeyCode() == evt.VK_ENTER && jTFCod.getText() != null){
            preencherCampos();
        }
    }//GEN-LAST:event_jTFCodKeyPressed

    private void jTFCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCargoKeyPressed
        String aux = jTFCargo.getText();
        if(evt.getKeyCode() == evt.VK_ENTER && jTFCargo.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório!", "Aviso", JOptionPane.OK_OPTION);
        }else if(evt.getKeyCode() == evt.VK_ENTER){
            jBtnSalvar.requestFocus();
        }
    }//GEN-LAST:event_jTFCargoKeyPressed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        CargoDAO cargoDAO = new CargoDAO();
        PesquisaTableModel etm = new PesquisaTableModel(cargoDAO.selectAll(), colunas, modelo);
        Pesquisar p = new Pesquisar(titulo, etm, this);
        auxTP.desktopPrincipal.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnSalvarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if (!jTFCod.getText().equalsIgnoreCase("")) {
                alterarCargo();
            }else{
                cadastrarCargo();
            }
        }
    }//GEN-LAST:event_jBtnSalvarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTFCargo;
    private javax.swing.JTextField jTFCod;
    // End of variables declaration//GEN-END:variables
}
