/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private JInternalFrame internalFrame = new JInternalFrame();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        desktopPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadEmp = new javax.swing.JMenuItem();
        menuCadCarg = new javax.swing.JMenuItem();
        menuCadFun = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAlterarSalario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRelEmp = new javax.swing.JMenuItem();
        menuRelCarg = new javax.swing.JMenuItem();
        menuRelFun = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPrincipalLayout = new javax.swing.GroupLayout(desktopPrincipal);
        desktopPrincipal.setLayout(desktopPrincipalLayout);
        desktopPrincipalLayout.setHorizontalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        desktopPrincipalLayout.setVerticalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(desktopPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktopPrincipal))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktopPrincipal))
        );

        jMenu1.setText("Cadastro");

        menuCadEmp.setText("Empresas");
        menuCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadEmpActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadEmp);

        menuCadCarg.setText("Cargos");
        menuCadCarg.setToolTipText("");
        menuCadCarg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCargActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadCarg);

        menuCadFun.setText("Funcionários");
        menuCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFunActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadFun);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentos");

        menuAlterarSalario.setText("Alteração de Salário");
        menuAlterarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarSalarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuAlterarSalario);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        menuRelEmp.setText("Empresas cadastradas");
        jMenu3.add(menuRelEmp);

        menuRelCarg.setText("Cargos cadastrados");
        jMenu3.add(menuRelCarg);

        menuRelFun.setText("Funcionários cadastrados");
        jMenu3.add(menuRelFun);

        jMenuBar1.add(jMenu3);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadEmpActionPerformed
        internalFrame = new CadEmpresas(this);
        desktopPrincipal.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_menuCadEmpActionPerformed

    private void menuCadCargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCargActionPerformed
        internalFrame = new CadCargos(this);
        desktopPrincipal.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_menuCadCargActionPerformed

    private void menuCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFunActionPerformed
        internalFrame = new CadFuncionarios(this);
        desktopPrincipal.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_menuCadFunActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        if(internalFrame.isVisible()){
            JOptionPane.showMessageDialog(null, "Todas as janelas devem ser fechadas primeiro!", "Aviso", JOptionPane.OK_OPTION);
        }else{
            this.dispose();
        }
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuAlterarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarSalarioActionPerformed
        internalFrame = new AlterarSalario(this);
        desktopPrincipal.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_menuAlterarSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPrincipal telaPrincipal = new TelaPrincipal();
                telaPrincipal.setVisible(true);
                telaPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktopPrincipal;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAlterarSalario;
    private javax.swing.JMenuItem menuCadCarg;
    private javax.swing.JMenuItem menuCadEmp;
    private javax.swing.JMenuItem menuCadFun;
    private javax.swing.JMenuItem menuRelCarg;
    private javax.swing.JMenuItem menuRelEmp;
    private javax.swing.JMenuItem menuRelFun;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
